### ISSUE TITLE
Refresh Button for Stats

### ISSUE THREAD

**Issue by the-rango** [JeffreyTrail/jt-carrier#1]

**Comment by Scott170c** [comment]
https://github.com/JeffreyTrail/jt-carrier/pull/11/commits/f8c401f29168bc6e5276a595c4e2f91f5562a29d
review and merge if nothing is broken

**Comment by Scott170c** [comment]
fixed https://github.com/JeffreyTrail/jt-carrier/commit/f8c401f29168bc6e5276a595c4e2f91f5562a29d
